### PR TITLE
Add missing steps to recover a password

### PR DESCRIPTION
**Pull request by PatrickLang**
When you have a dodgy wireless keyboard that occasionally drops keystrokes, sometimes you don't actually know your password. That's the excuse I use anyway.

Here's the steps to finish out the process on creator's update

### CODE REVIEW

**Comment by bitcrazed** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[commandline/WSL/user_support.md](https://github.com/PatrickLang/CommandLine-Documentation/blob/patch-2/commandline/WSL/user_support.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C21%5C44a4c0e9-f7fc-ae3e-a431-dcb870cfc899%5CPullRequest%5C201709210409337534-131%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qjJwJ9eUWFQ2sVGmOMv9aZF3ouOLJgegeLsscDQXuCM%3D&st=2017-09-21T04%3A05%3A26Z&se=2017-09-22T04%3A15%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bitcrazed** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[commandline/WSL/user_support.md](https://github.com/PatrickLang/CommandLine-Documentation/blob/patch-2/commandline/WSL/user_support.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C21%5C44a4c0e9-f7fc-ae3e-a431-dcb870cfc899%5CPullRequest%5C201709210410516106-131%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oeq5ufaqT2hpwHBkGXe4%2FjVLrwjWlYhzodh7jHlFObM%3D&st=2017-09-21T04%3A06%3A48Z&se=2017-09-22T04%3A16%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by PatrickLang** [comment]
ping @scooley is this your area now or another reviewer?

**Comment by bitcrazed** [comment]
Thanks for the improvements Patrick.

**Pull request merged**
